#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.4.0"
BASE_URL="https://github.com/kubecolor/kubecolor/releases/download/v${VERSION}/kubecolor_${VERSION}_"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
linux_amd64.tar.gz
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/kubecolor --kubecolor-version 2>/dev/null | tr -d '\r')"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current kubecolor version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for kubecolor" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading kubecolor version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

# SUFFIX will be "zip" when SUFFIX is something line *.zip, and it will not be
# changed if SUFFIX doesn't contain an extension
EXT="${SUFFIX##*.}"

if [ "$SUFFIX" = "zip" ]; then
    unzip archive >/dev/null
else
    tar xzf archive
fi

echo "Copying kubecolor to $BIN_PATH ..." >&2

if [ "$SUFFIX" = "zip" ]; then
    cp -f "kubecolor.exe" "$BIN_PATH"
else
    cp -f "kubecolor" "$BIN_PATH"
fi

chmod +x "$BIN_PATH/kubecolor"*

)

rm -rf "$TEMP_DIR"
