#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.3.7"
BASE_URL="https://github.com/vladimirvivien/ktop/releases/download/v${VERSION}/ktop_v${VERSION}_"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
linux_amd64.tar.gz
EOF
)"

# ktop has no command line option to check its version. Thus, we will only check for its presence.
[ ! -e "$BIN_PATH"/ktop ] || exit 0

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for ktop" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading ktop version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

tar xzf archive

echo "Copying ktop to $BIN_PATH ..." >&2
cp -f "ktop" "$BIN_PATH"

chmod +x "$BIN_PATH/ktop"

)

rm -rf "$TEMP_DIR"
