#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="1.7.1"
BASE_URL="https://github.com/jqlang/jq/releases/download/jq-${VERSION}/jq-"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
linux-amd64
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/jq --version 2>/dev/null | tr -d '\r' | cut -d- -f2)"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current jq version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for jq" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading jq version $VERSION ..." >&2
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"

# EXT will be ".exe" when SUFFIX is something line *.exe, and it will be
# an empty string if SUFFIX doesn't contain an extension
EXT=".${SUFFIX##*.}"
[ "$EXT" != ".$SUFFIX" ] || EXT=""

geturl "$URL" > "$BIN_PATH/jq$EXT"
chmod +x "$BIN_PATH/jq$EXT"
