#!/bin/sh

URL="https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"

if ! command -v unzip >/dev/null 2>&1; then
    echo "Error: could not find command 'unzip'" >&2
    exit 1
fi


set -e

echo "Downloading AWS CLI ..." >&2
TEMP_DIR="$(mktemp --directory)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

unzip -qq archive

if [ -e /usr/local/bin/aws ]; then
    echo "Updating ..." >&2
    sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
else
    echo "Installing ..." >&2
    sudo ./aws/install
fi

)

rm -rf "$TEMP_DIR"
