#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.12.0"
BASE_URL="https://github.com/wagoodman/dive/releases/download/v${VERSION}/dive_${VERSION}_"
SUFFIX="$(cat <<EOF
Darwin:x86_64
darwin_amd64.tar.gz
GNU_Linux:x86_64
linux_amd64.tar.gz
Cygwin:x86_64
windows_amd64.zip
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/dive --version 2>/dev/null | tr -d '\r' | awk '{print $2}')"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current dive version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for dive" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading dive version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

EXT="${SUFFIX##*.}"

if [ "$EXT" = "zip" ]; then
    unzip archive >/dev/null
else
    tar xzf archive
fi

echo "Copying dive to $BIN_PATH ..." >&2
cp -f "dive"* "$BIN_PATH"
chmod +x "$BIN_PATH/dive"*

)

rm -rf "$TEMP_DIR"
