#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.5.0"
BASE_URL="https://github.com/robinovitch61/kl/releases/download/v${VERSION}/kl_${VERSION}_"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
Linux_x86_64.tar.gz
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/kl --version 2>/dev/null | tr -d '\r' | awk '{print $NF}' | tr -d 'v')"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current kl version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for kl" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading kl version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

tar xzf archive

echo "Copying kl to $BIN_PATH ..." >&2
cp -f "kl" "$BIN_PATH"

chmod +x "$BIN_PATH/kl"

)

rm -rf "$TEMP_DIR"
