#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="4.44.6"
BASE_URL="https://github.com/mikefarah/yq/releases/download/v${VERSION}/yq_"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
linux_amd64
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/yq --version 2>/dev/null | tr -d '\r' | awk '{print $NF}' | tr -d 'v')"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current yq version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for yq" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading yq version $VERSION ..." >&2
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"

# EXT will be ".exe" when SUFFIX is something line *.exe, and it will be
# an empty string if SUFFIX doesn't contain an extension
EXT=".${SUFFIX##*.}"
[ "$EXT" != ".$SUFFIX" ] || EXT=""

geturl "$URL" > "$BIN_PATH/yq$EXT"
chmod +x "$BIN_PATH/yq$EXT"
