#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.9.3"
BASE_URL="https://github.com/cantino/mcfly/releases/download/v${VERSION}/mcfly-v${VERSION}-"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
x86_64-unknown-linux-musl.tar.gz
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/mcfly --version 2>/dev/null | tr -d '\r' | awk '{print $NF}')"; then
    [ "$CUR_VERSION" != "$VERSION" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current mcfly version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for mcfly" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading mcfly version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

tar xzf archive

echo "Copying mcfly to $BIN_PATH ..." >&2
cp -f "mcfly" "$BIN_PATH"

chmod +x "$BIN_PATH/mcfly"

)

rm -rf "$TEMP_DIR"
