#!/bin/sh

set -e

BIN_PATH="$1"
VERSION="0.8.0"
# version number is broken in kube-capacity v0.8.0 and reports version 0.7.4 instead
VERSION_REPORT="0.7.4"
BASE_URL="https://github.com/robscott/kube-capacity/releases/download/v${VERSION}/kube-capacity_v${VERSION}_"
SUFFIX="$(cat <<EOF
GNU_Linux:x86_64
linux_x86_64.tar.gz
EOF
)"

if CUR_VERSION="$("$BIN_PATH"/kube-capacity version 2>/dev/null | tr -d '\r' | awk '{print $NF}' | tr -d 'v')"; then
    [ "$CUR_VERSION" != "$VERSION_REPORT" ] || exit 0
    [ -z "$CUR_VERSION" ] || echo "The current kube-capacity version '$CUR_VERSION' does not match the desired version '$VERSION'" >&2
fi

SUFFIX="$(echo "$SUFFIX" | sed -n -E "/$(echo "$(uname --operating-system)" | tr '/' '_'):$(uname --machine)/{n;p;}")"
if [ -z "$SUFFIX" ]; then
    echo "$0: Error: unknown platform for kube-capacity" >&2
    exit 1
fi

URL="$BASE_URL$SUFFIX"

echo "Downloading kube-capacity version $VERSION ..." >&2
TEMP_DIR="$(mktemp --directory)"
# convert to absolute
BIN_PATH="$(cd "$BIN_PATH"; pwd)"
# run in subshell to preserve pwd
(

cd "$TEMP_DIR"
geturl "$URL" > archive
echo "Extracting the archive ..." >&2

tar xzf archive

echo "Copying kube-capacity to $BIN_PATH ..." >&2
cp -f "kube-capacity" "$BIN_PATH"

chmod +x "$BIN_PATH/kube-capacity"

)

rm -rf "$TEMP_DIR"
