#!/usr/bin/env bash

lastbuild() {

    local BLD
    local MSK
    local BAS
    local LST
    local BID
    local ARCH

    if [ "$1" = "lin" ]; then
        ARCH="x86_64_Linux"
        shift
    elif [ "$1" = "win" ]; then
       ARCH="i686_win64"
       shift
    fi

    if [ -n "$1" ] && [ "$1" = "list" ]; then
        LST=1
        shift
    fi

    if [ -n "$LST" ] && [ -n "$1" ]; then
        ectool --server artemis.nimbus.beescloud.com getProperties --path '/server/CommanderReleases' \
            | grep -oP '<propertyName>\K[^<]+' \
            | sort --version-sort
        return $?
    fi

    if [ -n "$1" ] && [ "$(echo "$1" | cut -d- -f1)" = "commander" ]; then
        BID="$1"
        shift
    # if $1 is a number (and no ".")
    elif [ -n "$1" ] && [ "$1" -eq "$1" ] 2>/dev/null && [ "$1" = "${1#*.}" ]; then
        BID="commander-*.$1-*"
        shift
    # if $1 is a version
    elif echo "$1" | grep --silent -P '^(\d\.?)+$'; then
        BID="$(ectool --server artemis.nimbus.beescloud.com getProperty "/server/CommanderReleases/$1")"
        shift
    else
        BID='commander-main.*'
    fi

    if [ -z "$ARCH" ]; then
        if [ "$(uname -o)" = "Cygwin" ]; then
            ARCH="i686_win64"
        else
            ARCH="x86_64_Linux"
        fi
    fi

    BLD="$BID/out/$ARCH/nimbus/install"

    if [ -z "$1" ] || [ "$1" = "common64" ] || [ "$1" = "common" ]; then
        MSK="CloudBeesFlow-x64-*"
    elif [ "$1" = "agent" ]; then
        MSK="CloudBeesFlowAgent-x64-*"
    elif [ "$1" = "dois" ]; then
        MSK="CloudBees*Server-x64-*"
    elif [ "$1" = "dofs" ]; then
        MSK="CloudBeesFlowDevOpsForesightServer-x64-*"
    else
        echo 'Usage: lastbuild [list] [<build>] [common|agent|dois|dofs]' >&2
        return 1
    fi

    if [ -e /net/chronic3build ] || [ -e /mnt/chronic3build ] || [ -e /n/chronic3build ]; then
        if [ -e /n/chronic3build ]; then
            BLD="/n/chronic3build/$BLD/$MSK"
        elif [ -e /net/chronic3build ]; then
            BLD="/net/chronic3build/$BLD/$MSK"
        else
            BLD="/mnt/chronic3build/$BLD/$MSK"
        fi
        if [ -n "$LST" ]; then
            /bin/ls -t -1 $BLD | grep -v md5 | grep -v \\.sig | cut -d/ -f 4
            return 0
        fi
        BLD="$(/bin/ls -t -1 $BLD | grep -v md5 | grep -v \\.sig | head -1)"
    else
        if [ -n "$LST" ]; then
            ssh build@gw.nimbus.beescloud.com "/bin/ls -t -1 /mnt/chronic3build/$BLD/$MSK | grep -v md5 | grep -v \\\\.sig | cut -d/ -f 4"
            return 0
        fi
        echo "* Looking for the build on remote side..." >&2
        BLD="$(ssh build@gw.nimbus.beescloud.com "/bin/ls -t -1 /mnt/chronic3build/$BLD/$MSK | grep -v md5 | grep -v \\\\.sig | head -1")"
        BAS="$(echo "$BLD" | sed 's#^/[^/]\+/#/tmp/#')"
        if [ ! -e "$BAS" ]; then
            mkdir -p "$(dirname "$BAS")"
            echo "* Copying the build from remote side..." >&2
            scp "build@gw.nimbus.beescloud.com:$BLD" "$(dirname "$BAS")" >&2
        fi
        BLD="$BAS"
    fi

    echo "Using build: `echo "$BLD" | cut -d/ -f4`" >&2
    echo "File: `basename "$BLD"`" >&2
    echo "$BLD"
}

lastbuild "$@"
